import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { canonicalJson, type ProjectConfig, type Schema } from "@streamotter/contracts";

export const GENERATED_MARKER = "// @generated by streamotter generate";

/**
 * Which npm packages generated and scaffolded code imports StreamOtter from: the individual
 * `@streamotter/*` packages, or the all-in-one `streamotter` package (`streamotter/client`, …).
 */
export type PackageStyle = "scoped" | "streamotter";

/** Module specifiers for a package style. */
export function streamotterModules(style: PackageStyle = "scoped"): { client: string; gateway: string } {
  return style === "streamotter"
    ? { client: "streamotter/client", gateway: "streamotter/gateway" }
    : { client: "@streamotter/client", gateway: "@streamotter/gateway" };
}

/**
 * The package style of the project containing `directory` (which may not exist yet): "streamotter"
 * when the nearest package.json depends on `streamotter` and not on `@streamotter/client`.
 */
export function detectPackageStyle(directory: string): PackageStyle {
  let current = resolve(directory);
  for (;;) {
    const manifest = join(current, "package.json");
    if (existsSync(manifest)) {
      try {
        const json = JSON.parse(readFileSync(manifest, "utf8")) as Record<string, Record<string, string> | undefined>;
        const dependencies = { ...json["dependencies"], ...json["devDependencies"], ...json["peerDependencies"] };
        return "streamotter" in dependencies && !("@streamotter/client" in dependencies) ? "streamotter" : "scoped";
      } catch {
        return "scoped";
      }
    }
    const parent = dirname(current);
    if (parent === current) return "scoped";
    current = parent;
  }
}

const RESERVED = new Set([
  "AppChannels", "ChannelContract", "Client", "Subscription", "Array", "Boolean", "Date", "Error", "Function", "JSON", "Map",
  "Math", "Number", "Object", "Promise", "Record", "Set", "String", "Symbol"
]);
const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

export function fingerprint(config: unknown): string {
  return createHash("sha256").update(canonicalJson(config)).digest("hex");
}

function pascalCase(id: string): string {
  return id.split(/[-_]+/).filter(Boolean).map(part => part[0]!.toUpperCase() + part.slice(1)).join("");
}

/** Maps schema IDs to unique, valid, non-shadowing TypeScript type names. */
export function typeNames(schemaIds: readonly string[]): Map<string, string> {
  const names = new Map<string, string>();
  const used = new Set<string>();
  for (const id of schemaIds) {
    let name = pascalCase(id);
    if (RESERVED.has(name)) name = `${name}Schema`;
    let candidate = name;
    for (let suffix = 2; used.has(candidate); suffix++) candidate = `${name}${suffix}`;
    used.add(candidate);
    names.set(id, candidate);
  }
  return names;
}

function propertyKey(name: string): string {
  return IDENTIFIER.test(name) ? name : JSON.stringify(name);
}

function describe(schema: Schema): string | null {
  switch (schema.type) {
    case "string": {
      const parts = [];
      if (schema.minLength !== undefined) parts.push(`minLength ${schema.minLength}`);
      if (schema.maxLength !== undefined) parts.push(`maxLength ${schema.maxLength}`);
      return parts.length > 0 ? parts.join(", ") : null;
    }
    case "number":
    case "integer": {
      const parts: string[] = [schema.type];
      if (schema.minimum !== undefined) parts.push(`minimum ${schema.minimum}`);
      if (schema.maximum !== undefined) parts.push(`maximum ${schema.maximum}`);
      return schema.type === "integer" || parts.length > 1 ? parts.join(", ") : null;
    }
    case "array":
      return `maxItems ${schema.maxItems}`;
    default:
      return null;
  }
}

/** Renders a schema as a TypeScript type expression (type aliases, never interfaces, so values stay assignable to Json). */
export function renderType(schema: Schema, indent = ""): string {
  switch (schema.type) {
    case "string":
      return schema.enum !== undefined ? schema.enum.map(value => JSON.stringify(value)).join(" | ") : "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array": {
      const item = renderType(schema.items, indent);
      return /[|&]/.test(item) && !item.startsWith("{") ? `(${item})[]` : `${item}[]`;
    }
    case "object": {
      const entries = Object.entries(schema.properties);
      if (entries.length === 0) return "Record<string, never>";
      const inner = `${indent}  `;
      const lines = entries.map(([name, child]) => {
        const note = describe(child);
        const comment = note === null ? "" : `${inner}/** ${note} */\n`;
        const optional = schema.required.includes(name) ? "" : "?";
        return `${comment}${inner}${propertyKey(name)}${optional}: ${renderType(child, inner)};`;
      });
      return `{\n${lines.join("\n")}\n${indent}}`;
    }
    default:
      return "never";
  }
}

export interface GeneratedFile { path: string; content: string }

/**
 * Generates the application channel contract (AppChannels with each channel's
 * parameter type, payload type, and literal version) plus a vanilla TypeScript
 * integration example. Numeric ranges and string lengths remain runtime checks.
 */
export function generateFiles(config: ProjectConfig, options: { packages?: PackageStyle } = {}): GeneratedFile[] {
  const modules = streamotterModules(options.packages);
  const fp = fingerprint(config);
  const header = `${GENERATED_MARKER} (config sha256:${fp}). Do not edit; rerun the generator.\n`;
  const names = typeNames(Object.keys(config.schemas));
  const schemaTypes = Object.entries(config.schemas).map(([id, schema]) =>
    `/** Schema "${id}". */\nexport type ${names.get(id)} = ${renderType(schema)};`
  );
  const channels = Object.entries(config.channels).map(([name, channel]) =>
    `  ${propertyKey(name)}: ChannelContract<${names.get(channel.paramsSchema)}, ${names.get(channel.payloadSchema)}, ${channel.version}>;`
  );
  const versions = Object.entries(config.channels).map(([name, channel]) => `  ${propertyKey(name)}: ${channel.version}`);
  const types = [
    header,
    `import type { ChannelContract } from "${modules.client}";`,
    "",
    ...schemaTypes.flatMap(block => [block, ""]),
    `/** Channel contracts for createClient<AppChannels>(). Project "${config.projectId}". */`,
    "export type AppChannels = {",
    ...channels,
    "};",
    "",
    "/** Deployed channel versions; subscribe requests must name them exactly. */",
    "export const channelVersions = {",
    versions.join(",\n"),
    "} as const;",
    ""
  ].join("\n");

  const [firstName, firstChannel] = Object.entries(config.channels)[0] ?? [];
  const paramsSchema = firstChannel === undefined ? undefined : config.schemas[firstChannel.paramsSchema];
  const exampleParams = paramsSchema?.type === "object"
    ? `{ ${Object.entries(paramsSchema.properties).map(([key, schema]) =>
      `${propertyKey(key)}: ${schema.type === "string" ? (schema.enum?.[0] !== undefined ? JSON.stringify(schema.enum[0]) : `"example"`) : schema.type === "boolean" ? "true" : "1"}`).join(", ")} }`
    : "{}";
  const example = firstName === undefined ? `${header}\nexport {};\n` : [
    header,
    `import { createClient, type StreamError, type SubscriptionState } from "${modules.client}";`,
    `import { channelVersions, type AppChannels } from "./streamotter.generated.js";`,
    "",
    "/**",
    ` * Subscribes to "${firstName}" and returns a cleanup function. Replace render/showState/showError`,
    " * with your view code. getToken must return your application's session token for the gateway.",
    " */",
    `export async function mount${pascalCase(firstName)}(options: {`,
    "  origin: string;",
    `  params: AppChannels[${JSON.stringify(firstName)}]["params"];`,
    "  getToken: (signal: AbortSignal) => Promise<string>;",
    `  render: (data: AppChannels[${JSON.stringify(firstName)}]["data"]) => void;`,
    "  showState?: (state: SubscriptionState) => void;",
    "  showError?: (error: StreamError) => void;",
    "}): Promise<() => Promise<void>> {",
    "  const client = createClient<AppChannels>({ origin: options.origin, getToken: ({ signal }) => options.getToken(signal) });",
    `  const subscription = client.subscribe(${JSON.stringify(firstName)}, {`,
    `    channelVersion: channelVersions[${JSON.stringify(firstName)}],`,
    "    params: options.params",
    "  });",
    "  subscription.on(\"data\", event => options.render(event.data));",
    "  subscription.on(\"state\", ({ state }) => options.showState?.(state));",
    "  subscription.on(\"error\", error => options.showError?.(error));",
    "  try {",
    "    await subscription.ready({ timeoutMs: 30_000 });",
    "  } catch (error) {",
    "    await subscription.unsubscribe();",
    "    await client.close();",
    "    throw error;",
    "  }",
    "  return async () => {",
    "    await subscription.unsubscribe();",
    "    await client.close();",
    "  };",
    "}",
    "",
    `// Example: await mount${pascalCase(firstName)}({ origin: "http://localhost:${config.gateway.port}", params: ${exampleParams}, getToken, render });`,
    ""
  ].join("\n");

  return [
    { path: "streamotter.generated.ts", content: types },
    { path: "streamotter.client.example.ts", content: example }
  ];
}
